apiVersion: v1
kind: ServiceAccount
metadata:
  # El nombre que usarás para referenciar esta ServiceAccount
  name: cicd-serviceaccount
  # Opcional: El namespace donde se creará. Si se omite, se usará 'default'.
  namespace: daniel-lopez-fisa-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-binding
  namespace: daniel-lopez-fisa-dev
subjects:
- kind: ServiceAccount
  name: cicd-serviceaccount # La cuenta de servicio que creamos
  namespace: daniel-lopez-fisa-dev
roleRef:
  kind: ClusterRole
  name: edit # El rol que creamos
  apiGroup: rbac.authorization.k8s.io